---
{% raw -%}
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  tasks:
    - name: Destroy molecule instance(s)
      docker_container:
        name: "{{ item.name }}"
        docker_host: "{{ item.docker_host | default(lookup('env', 'DOCKER_HOST') or 'unix://var/run/docker.sock') }}"
        state: absent
        cacert_path: "{{ lookup('env', 'DOCKER_CERT_PATH_CA') | default(omit) }}"
        cert_path: "{{ lookup('env', 'DOCKER_CERT_PATH_CERT') | default(omit) }}"
        key_path: "{{ lookup('env', 'DOCKER_CERT_PATH_KEY') | default(omit) }}"
        ssl_version: "{{ item.docker_ssl_version | default(omit)}}"
        tls: "{{ lookup('env', 'DOCKER_TLS') | bool }}"
        force_kill: "{{ item.force_kill | default(true) }}"
      register: server
      with_items: "{{ molecule_yml.platforms }}"

    - name: Delete docker network(s)
      docker_network:
        name: "{{ item }}"
        docker_host: "{{ item.docker_host | default(lookup('env', 'DOCKER_HOST') or 'unix://var/run/docker.sock') }}"
        cacert_path: "{{ lookup('env', 'DOCKER_CERT_PATH_CA') | default(omit) }}"
        cert_path: "{{ lookup('env', 'DOCKER_CERT_PATH_CERT') | default(omit) }}"
        key_path: "{{ lookup('env', 'DOCKER_CERT_PATH_KEY') | default(omit) }}"
        ssl_version: "{{ item.docker_ssl_version | default(omit)}}"
        tls: "{{ lookup('env', 'DOCKER_TLS') | bool }}"
        state: absent
      with_items: "{{ molecule_yml.platforms | molecule_get_docker_networks }}"
{%- endraw %}
